# Generated by Django 4.2.7 on 2023-11-21 15:20

from django.db import migrations, models
import mainPage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название Еды:')),
                ('price', models.IntegerField(verbose_name='Цена Еды:')),
                ('image', models.ImageField(null=True, upload_to=mainPage.models.upload_to, verbose_name='Картинка Еды:')),
            ],
            options={
                'verbose_name': 'ФастФуд',
                'verbose_name_plural': 'ФастФуда',
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Категория ФастФуда:')),
            ],
            options={
                'verbose_name': 'Категория ФастФуда',
                'verbose_name_plural': 'Категория ФастФуда',
            },
        ),
    ]
