# Generated by Django 4.2.7 on 2023-11-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_dish_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='anchor',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Якорь'),
        ),
    ]
