# Generated by Django 4.2.7 on 2023-11-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0004_alter_foodcategory_options_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
