# Generated by Django 4.2.7 on 2023-11-30 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainPage', '0005_comments_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='liked_by_users',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
