# Generated by Django 4.2.7 on 2023-11-30 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0006_comments_liked_by_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='liked_by_users',
        ),
    ]
